"""LLM judge client for evaluating free-form text outputs."""

import logging
import re

from gitbench.harness.model import ModelInterface
from gitbench.harness.types import ModelMessage

logger = logging.getLogger(__name__)

JUDGE_COMMIT_MESSAGE_PROMPT = """You are evaluating the quality of a commit message for a git diff.

Score the commit message on a scale from 0.0 to 1.0 based on:
- Does it accurately describe the changes in the diff?
- Is it concise and well-structured?
- Does it follow conventional commit message format?
- Does it capture the intent and scope of the change?

Return ONLY a number between 0.0 and 1.0. Do not include any explanation.

Git diff:
{diff}

Commit message:
{message}

Score:"""


class JudgeClient:
    """Wraps a model client to evaluate free-form text outputs using an LLM judge.

    The judge is a separate (typically cheaper) model that rates the quality
    of a model-under-test's output in the context of a given diff.
    """

    def __init__(self, model_client: ModelInterface) -> None:
        """Initialise the judge client.

        Args:
            model_client: The model adapter to call for evaluation.
                Should be a cheap/fast model configured via the judge profile.
        """
        self._model_client = model_client

    def evaluate_commit_message(self, diff: str, message: str) -> float:
        """Evaluate a commit message against a git diff.

        Args:
            diff: The git diff to evaluate against.
            message: The commit message generated by the model under test.

        Returns:
            A float between 0.0 and 1.0 rating how well the message
            describes the diff.

        Raises:
            ValueError: If the judge response cannot be parsed as a number.
        """
        prompt = JUDGE_COMMIT_MESSAGE_PROMPT.format(diff=diff, message=message)
        messages = [ModelMessage(role="user", content=prompt)]

        try:
            response = self._model_client.generate(messages)
        except Exception as exc:
            logger.warning(
                "Judge call failed on first attempt: %s. Retrying once...", exc
            )
            try:
                response = self._model_client.generate(messages)
            except Exception as exc2:
                raise ValueError(f"Judge call failed after retry: {exc2}") from exc2

        if isinstance(response, dict):
            text = response.get("text", response.get("content", ""))
        else:
            text = str(response)

        return self._parse_score(text)

    def _parse_score(self, text: str) -> float:
        """Parse a numeric score from the judge model response.

        Args:
            text: The raw response text from the judge model.

        Returns:
            A float between 0.0 and 1.0.

        Raises:
            ValueError: If no numeric score can be extracted.
        """
        # Try to find a float number in the response (optionally signed)
        match = re.search(r"(-?\d+(?:\.\d+)?)", text)
        if not match:
            raise ValueError(
                f"Judge response could not be parsed as a number: {text!r}"
            )

        score = float(match.group(1))

        # Clamp to valid range
        if score < 0.0:
            score = 0.0
        elif score > 1.0:
            score = 1.0

        return score
